---
title: "BaseLine_abandono_año_anterior"
author: "Matias Deheza"
date: "19 April 2017"
output: html_document
---

```{r}
library(readr)
df_all_secundario<- read_csv("df_all.csv", col_types = cols(id = col_number(),
                                                            sec_hs_pro_ncub = col_number(),
                                                            sec_hs_otros_ncub = col_number()))

```

Separa data sets de entrenamiento

```{r}
library(dplyr)
df_secundario_filtrado_resto <- df_all_secundario  %>% filter(anio != 2015)
df_secundario_filtrado_2015 <- df_all_secundario  %>% filter(anio == 2015)

```

Estimacion basada en anio anterior
```{r}
df_secundario_filtrado_anioAnterior<- df_all_secundario %>% filter(anio == 2014)%>%select(id,abandono)
```

Join
```{r}
df_join <- merge(df_secundario_filtrado_2015,df_secundario_filtrado_anioAnterior, by = "id")
df_join<- df_join %>%select(id,abandono=abandono.x,prediccion=abandono.y)

```

Metricas
```{r}

df_join<- df_join %>%mutate(errorAbsoluto= abs(abandono - prediccion)) %>%mutate(porcentajeError= 100*errorAbsoluto/abandono) 

#Mean Absolute error
MAE <- mean(df_join$errorAbsoluto)
#mean(df_join$porcentajeError)

#Root mean absolute error
RMSE1 <- sqrt(mean(df_join$errorAbsoluto^2))

#Root mean absolute error - Considerando la cantidad de filas
RMSE2 <- sqrt(mean(df_join$errorAbsoluto^2/length(df_join)))

errores <- data.frame(MAE,RMSE1,RMSE2)
errores

##No nos interesa el % tanto como nos interesa el absoluto???? Pregunta para evaluar
```

```{r}

sum_abandono <- sum(df_join$abandono)
sum_prediccion <-sum(df_join$prediccion)
resta <-sum(df_join$abandono)-sum(df_join$prediccion)

errores_acumulado <- data.frame(sum_abandono,sum_prediccion,resta)
errores_acumulado
```
